/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120056-g6e8bd5dd25-20250628"
#endif /* AVUTIL_FFVERSION_H */
